---
language: python
python: "2.7"
os:
- linux
- osx
before_install:
  # install libxml dependency binaries
  - sudo apt-get install libxml2 libxml2-dev libxslt-dev python-dev

  # build/install current version of libxml
  - sudo CFLAGS="-O0" pip install lxml --upgrade

  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # build/install current version of Ansible
  - pip install ansible

script:
  # log version of Ansible
  - ansible --version

  # change directory to test playbook
  - cd tests

  # Check the role/playbook's syntax.
  - ansible-playbook -i inventory test.yml --syntax-check --list-tasks -vvvv

  # Run the miscellaneous tests.
  - "ansible-playbook -i inventory test.yml"
...
